app/Controllers/SpaTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using app.Data;
using app.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace app.Controllers
{
    public class SpaTypesController : Controller
    {
        private readonly SpaContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SpaTypesController(SpaContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: SpaTypes
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchString)
        {
            var spaTypes =  await _context.SpaType.ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                spaTypes = spaTypes.FindAll(spaType => spaType.Name.Contains(searchString));
            }

            return View(spaTypes);
        }

        // GET: SpaTypes/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spaType = await _context.SpaType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spaType == null)
            {
                return NotFound();
            }

            return View(spaType);
        }

        // GET: SpaTypes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: SpaTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,MinAge")] SpaType spaType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spaType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spaType);
        }

        // GET: SpaTypes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spaType = await _context.SpaType.FindAsync(id);
            if (spaType == null)
            {
                return NotFound();
            }
            return View(spaType);
        }

        // POST: SpaTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,MinAge")] SpaType spaType)
        {
            if (id != spaType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spaType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpaTypeExists(spaType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spaType);
        }

        // GET: SpaTypes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spaType = await _context.SpaType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spaType == null)
            {
                return NotFound();
            }

            return View(spaType);
        }

        // POST: SpaTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var spaType = await _context.SpaType.FindAsync(id);
                _context.SpaType.Remove(spaType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return new CanNotDeleteViewResult("CanNotDelete", "Can not delete this spa type because there are spas attached to it.");
            }
        }

        [Authorize(Roles = "Admin")]
        private bool SpaTypeExists(int id)
        {
            return _context.SpaType.Any(e => e.Id == id);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetSpaTypesList()
        {
            var a = _context.SpaType.Select(x => x.Name).ToList();
            return Json(_context.SpaType.Select(x => x.Name).ToList());
        }

        [Authorize(Roles = "Admin")]
        public JsonResult GetSpasPerSpaTypeGraph()
        {

            return Json((from t in _context.SpaType
                         join s in _context.Spas
                         on t.Id equals s.SpaType.Id
                         select new
                         {
                             SpaType = t.Name,
                             SpaName = s.Name

                         })
                     .GroupBy(x => x.SpaType)
                     .Select(t => new { SpaType = t.Key, NumOfSpas = t.Count() }));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetSpaTypeList()
        {
            return Json(_context.SpaType.Select(g => g.Name).ToList());
        }
    }
}

app/Controllers/SpasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using app.Data;
using app.Models;
using internetiot.Handlers;
using Microsoft.AspNetCore.Authorization;
using app.Services;
using Microsoft.AspNetCore.Identity;

namespace app.Controllers
{
    public class SpasController : Controller
    {
        private readonly SpaContext _context;
        private readonly RecommendationService _rc;
        private readonly UserManager<ApplicationUser> _userManager;

        public SpasController(SpaContext context, RecommendationService rc, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _rc = rc;
            _userManager = userManager;
        }

        // GET: Spas
        public async Task<IActionResult> Index(string spaName, int patients, int maxPrice, string address)
        {
            var spas = _context.Spas.Include("SpaType");

            if (!String.IsNullOrEmpty(spaName))
            {
                spas = spas.Where(s => s.Name.Contains(spaName));
            }
            if (!String.IsNullOrEmpty(address))
            {
                spas = spas.Where(s => s.Address.Contains(address));
            }
            if (patients > 0)
            {
                spas = spas.Where(s => (s.MaxPatients >= patients));
            }
            if (maxPrice > 0)
            {
                spas = spas.Where(s => s.PricePerPatient <= maxPrice);
            }

            return View(await spas.ToListAsync());
        }

        // GET: Spas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NotFoundError", "Spa was not found");
            }

            var spa = await _context.Spas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spa == null)
            {
                return new NotFoundViewResult("NotFoundError", "Spa was not found");
            }

            return View(spa);
        }

        // GET: Spas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Description,MaxPatients,PricePerPatient,Duration,ImgUrl, SpaType")] Spa spa)
        {
            string tname = ModelState.ToList().First(x => x.Key == "SpaType.Name").Value.RawValue.ToString();
            var type = _context.SpaType.Where(g => g.Name == tname);
            if (type.Count() != 0)
            {
                if (ModelState.IsValid)
                {
                    spa.SpaType = type.ToList()[0];
                    _context.Add(spa);
                    await _context.SaveChangesAsync();
                    FaceBookHandler.PostMessage(spa);
                    return RedirectToAction(nameof(Index));
                }

                return View(spa);
            }
            else
            {
                return new NotFoundViewResult("NotFoundError", "SpaType was not found");
            }

        }

        // GET: Spas/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NotFoundError", "Spa was not found");
            }

            var spa = _context.Spas.Include(r => r.SpaType).Where(r => r.Id == id);
            if (spa.Count() == 0)
            {
                return new NotFoundViewResult("NotFoundError", "Room was not found");
            }
            return View(spa.ToList()[0]);
        }

        // POST: Spas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Description,MaxPatients,PricePerPatient,Duration,ImgUrl,SpaType")] Spa spa)
        {
            if (id != spa.Id)
            {
                return new NotFoundViewResult("NotFoundError", "Spa was not found");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string tname = ModelState.ToList().First(x => x.Key == "SpaType.Name").Value.RawValue.ToString();
                    var type = _context.SpaType.Where(g => g.Name == tname);
                    if (type.Count() != 0)
                    {
                        spa.SpaType = type.ToList()[0];
                        _context.Update(spa);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        return new NotFoundViewResult("NotFoundError", "SpaType was not found");
                    }

                }
                catch (DbUpdateConcurrencyException)
                {

                    return new NotFoundViewResult("NotFoundError", "Room was not found");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spa);
        }

        // GET: Spas/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spa = await _context.Spas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spa == null)
            {
                return NotFound();
            }

            return View(spa);
        }

        // POST: Spas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var spa = await _context.Spas.FindAsync(id);
                _context.Spas.Remove(spa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                return new CanNotDeleteViewResult("CanNotDelete", "Can not delete this spa because there are reserved appointments attached to it.");
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Statistics(string spaName, int patients, int maxPrice, string spaType)
        {
            var spaRooms = from r in _context.Spas
                           select r;

            if (!String.IsNullOrEmpty(spaName))
            {
                spaRooms = spaRooms.Where(s => s.Name.Contains(spaName));
            }

            if (patients > 0)
            {
                spaRooms = spaRooms.Where(s =>
                    (s.MaxPatients >= patients));
            }

            if (maxPrice > 0)
            {
                spaRooms = spaRooms.Where(s => s.PricePerPatient <= maxPrice);
            }

            if (!String.IsNullOrEmpty(spaType))
            {
                spaRooms = spaRooms.Where(s => s.SpaType.Name.Equals(spaType));
            }

            return View(await spaRooms.Include(r => r.SpaType).ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public JsonResult MostProfitableSpas()
        {
            var result = this._context.Reservations.GroupBy(x => x.Spa.Name).Select(s =>
            new
            {
                spaName = s.First().Spa.Name,
                Profit = s.Sum(p => p.TotalPrice)
            }).OrderByDescending(x => x.Profit).Take(5).ToList();
            
            return Json(result);
        }

        private bool SpaExists(int id)
        {
            return _context.Spas.Any(e => e.Id == id);
        }

        [HttpGet]
        [Authorize]
        public async Task<JsonResult> UserRecommendedSpas()
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            var all_spas = _context.Spas.ToList();
            var all_reservations = _context.Reservations.Include(x => x.Spa.SpaType).ToList();
            var user_interests = _context.Reservations.Where(r => r.User.Id == user.Id).Select(x => x.Spa.SpaType).Distinct().ToList();
            this._rc.Train(all_reservations, user_interests);
            var recommended = this._rc.PredictRecommendedSpass(all_spas).Take(3).ToList();

            return Json(recommended.Select(x => x.Id));
        }
    }
}

app/Views/Shared/CanNotDelete.cshtml
@{
	ViewData["Title"] = "Unable to delete";
}
<h3>@ViewData["Message"]</h3>

app/Views/Shared/NotFoundError.cshtml
@{
    ViewData["Title"] = "Not Found";
}
<h3>@ViewData["Message"]</h3>

app/Views/Shared/PermissionDeniedError.cshtml
@{
    ViewData["Title"] = "Permission Denied";
}
<h3>@ViewData["Message"]</h3>

app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - app</title>

    <!-- Project's design (fonts) -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="~/Scripts/app.js"></script>
    <link href="~/Content/fonts.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/main.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home Page</a>
            </div>
            <div class="navbar-collapse collapse">
                <partial name="_LoginPartial" />
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a></li>
                    <li><a asp-area="" asp-controller="Spas" asp-action="Index">Spas</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="SpaTypes" asp-action="Index">Spa Types</a></li>
                        <li><a asp-controller="Spas" asp-action="Statistics">Statistics</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center><p>&copy; @DateTime.Now.Year SpaAdvisor ALL RIGHTS RESERVED</p></center>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>